### ISSUE TITLE
Rtti uses `util` causing issues in Webpack 5

### ISSUE THREAD

**Issue by ray-vgw** [yortus/rtti#18]
HI @yortus  :)

We are using your other lib, http-schemas, that relies on rtti.  We are using this in a browser SPA that relies on Webpack 5.  Webpack 5 has stopped providing polyfils for some node based libraries like `util`.  Is it possible to change the requirement of this library away from using `util`?

```
RR! Module not found: Error: Can't resolve 'util' in '/Users/ray/source/xxx/shared/http/node_modules/rtti/dist/commonjs'
ERR! 
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR! 
ERR! If you want to include a polyfill, you need to:
ERR! 	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
ERR! 	- install 'util'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR! 	resolve.fallback: { "util": false }
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve 'util' in '/Users/xxx/shared/http/node_modules/rtti/dist/commonjs'
ERR! 

```

**Comment by yortus** [comment]
Thanks @ray-vgw, this has been on the todo list for a while. As of `rtti@1.1.3` and `http-schemas@0.13.1`, this package no longer has any runtime deps (removed both `util.inspect` and `lodash.cloneDeep`).

**Comment by ray-vgw** [comment]
Thank you!
